- name: Commit and Push Changes
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "github-actions@github.com"
    git add README.md
    git commit -m "Auto-update README" || echo "No changes to commit"
    git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
